# NIFTY details ##
NIFTY_SELL_PE_OPTION = 'Nifty_Sell_PE_Option.json'
NIFTY_BUY_PE_OPTION = 'Nifty_Buy_PE_Option.json'
NIFTY_HEDGE_PE_OPTION = 'Nifty_Hedge_PE_Option.json'
NIFTY_SELL_PREMIUM_PRICE = 400
NIFTY_BUY_PREMIUM_PRICE = 200
NIFTY_HEDGE_PREMIUM_PRICE = 2
NIFTY = 'NIFTY'
NSE_NIFTY50_INDEX = 'NSE:NIFTY50-INDEX'
NIFTY_EXPIRY_DAY = 16

# FINNIFTY details ##
FINNIFTY_SELL_PE_OPTION = 'FinNifty_Sell_PE_Option.json'
FINNIFTY_BUY_PE_OPTION = 'FinNifty_Buy_PE_Option.json'
FINNIFTY_HEDGE_PE_OPTION = 'FinNifty_Hedge_PE_Option.json'
FINNIFTY_SELL_PREMIUM_PRICE = 300
FINNIFTY_BUY_PREMIUM_PRICE = 150
FINNIFTY_HEDGE_PREMIUM_PRICE = 2
FINNIFTY = 'FINNIFTY'
NSE_FINNIFTY_INDEX = 'NSE:FINNIFTY-INDEX'
FINNIFTY_EXPIRY_DAY = 2

# BANKNIFTY DETAILS #
BANKNIFTY_SELL_PE_OPTION = 'BankNifty_Sell_PE_Option.json'
BANKNIFTY_BUY_PE_OPTION = 'BankNifty_Buy_PE_Option.json'
BANKNIFTY_HEDGE_PE_OPTION = 'BankNifty_Hedge_PE_Option.json'
BANKNIFTY_SELL_PREMIUM_PRICE = 1000
BANKNIFTY_BUY_PREMIUM_PRICE = 400
BANKNIFTY_HEDGE_PREMIUM_PRICE = 10
BANK_NIFTY_EXPIRY_DAY = 31
NSE_NIFTYBANK_INDEX = 'NSE:NIFTYBANK-INDEX'
BANKNIFTY = 'BANKNIFTY'

# MIDCPNIFTY DETAILS
MIDCPNIFTY_BUY_PE_OPTION = 'MIDCPNIFTY_Buy_PE_Option.json'
MIDCPNIFTY_SELL_PE_OPTION = 'MIDCPNIFTY_Sell_PE_Option.json'
MIDCPNIFTY_HEDGE_PE_OPTION = 'MIDCPNIFTY_Hedge_PE_Option.json'
MIDCPNIFTY_EXPIRY_DAY = 15
MIDCPNIFTY_SELL_PREMIUM_PRICE = 100
MIDCPNIFTY_BUY_PREMIUM_PRICE = 200
MIDCPNIFTY_HEDGE_PREMIUM_PRICE = 2
MIDCPNIFTY = 'MIDCPNIFTY'
NSE_MIDCPNIFTY_INDEX = 'NSE:MIDCPNIFTY-INDEX'

# SENSEX DETAILS
SENSEX_BUY_PE_OPTION = 'Sensex_Buy_PE_Option.json'
SENSEX_SELL_PE_OPTION = 'Sensex_Sell_PE_Option.json'
SENSEX_SELL_CE_OPTION = 'Sensex_Sell_CE_Option.json'
SENSEX_HEDGE_PE_OPTION = 'Sensex_Hedge_PE_Option.json'
SENSEX_SELL_PREMIUM_PRICE = 900
SENSEX_BUY_PREMIUM_PRICE = 200
SENSEX_HEDGE_PREMIUM_PRICE = 10
SENSEX = 'SENSEX'
BSE_SENSEX_INDEX = 'BSE:SENSEX-INDEX'
SENSEX_EXPIRY_DAY = 21


# COMMON DETAILS ##
CONFIG_JSON = 'config.json'
TRADE_SQUARE_OFF = '15:25'
TRADE_EXECUTION_TIME = '09:20'
EXPIRY_YEAR = 2025
EXPIRY_MONTH = 1
PAPER_TRADE = 'YES'  # NO YES
FNO_SEGMENT_NO = 14
WAITING_TIME = 0
PRODUCT_TYPE = 'MARGIN'  # INTRADAY
